[simulation]
month = "june"
time_interval= "hours"
delay_period_s = 2
energy_source = "solar"

[charge_point]
area_of_solar_panel= 1.3
num_solar_panels= 10
max_charge_power_kw= 7
efficiency= 0.5
storage_capacity_kwh= 12.5
current_storage_capacity_kwh= 6

[vehicle]
battery_size_kwh= 60
time_to_charge_hours= 8
average_power_consumption_ev_kw= 20
current_battery_level_kwh= 30
    

